"""Initial migration

Revision ID: 6a144cfe582d
Revises: 
Create Date: 2026-02-26 17:34:50.862445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a144cfe582d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klines',
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('taker_buy_base_volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('taker_buy_quote_volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('exchange', 'symbol', 'interval', 'open_time')
    )
    op.create_index('idx_klines_latest', 'klines', ['exchange', 'symbol', 'interval', sa.literal_column('open_time DESC')], unique=False)

    # Enable TimescaleDB extension and create hypertable
    # Note: CREATE EXTENSION usually requires superuser privileges. 
    # Ensure 'timescaledb' extension is installed in the database manually if this fails.
    # op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")
    
    # TimescaleDB hypertable creation
    # Uncomment the following line if TimescaleDB extension is installed and enabled
    # op.execute("SELECT create_hypertable('klines', 'open_time', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);")

    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('margin', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('margin_mode', sa.String(length=20), nullable=True),
    sa.Column('leverage', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', 'side', name='uq_positions_exchange_symbol_side')
    )
    op.create_index('idx_positions_exchange_updated', 'positions', ['exchange', 'updated_at'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_events_created_severity', 'risk_events', ['created_at', 'severity'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('max_position_size', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('allowed_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('time_in_force', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('filled', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('client_order_id', sa.String(length=100), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index('idx_orders_exchange_order_id', 'orders', ['exchange_order_id'], unique=False)
    op.create_index('idx_orders_exchange_symbol', 'orders', ['exchange', 'symbol'], unique=False)
    op.create_index('idx_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('idx_orders_strategy_created', 'orders', ['strategy_id', 'created_at'], unique=False)
    op.create_table('strategy_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_runs_strategy_started', 'strategy_runs', ['strategy_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fee_currency', sa.String(length=20), nullable=True),
    sa.Column('is_maker', sa.Boolean(), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exchange_trade_id', sa.String(length=100), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_exchange_symbol_executed', 'trades', ['exchange', 'symbol', sa.literal_column('executed_at DESC')], unique=False)
    op.create_index('idx_trades_exchange_trade_id', 'trades', ['exchange_trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_exchange_trade_id', table_name='trades')
    op.drop_index('idx_trades_exchange_symbol_executed', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_strategy_runs_strategy_started', table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_index('idx_orders_strategy_created', table_name='orders')
    op.drop_index('idx_orders_status_created', table_name='orders')
    op.drop_index('idx_orders_exchange_symbol', table_name='orders')
    op.drop_index('idx_orders_exchange_order_id', table_name='orders')
    op.drop_table('orders')
    op.drop_table('strategies')
    op.drop_index('idx_risk_events_created_severity', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index('idx_positions_exchange_updated', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_klines_latest', table_name='klines')
    op.drop_table('klines')
    # ### end Alembic commands ###
